name: "${name}"
version: ${version}
main: "org.purpurmc.purpurextras.PurpurExtras"
api-version: '1.21.4'
authors: [ YouHaveTrouble ]
description: "${description}"
bootstrapper: "org.purpurmc.purpurextras.PurpurExtrasBootstrap"