name: Feature request
description: Suggest an idea for PurpurExtras
body:
- type: markdown
  attributes:
    value: >
      Thank you for filling out a feature request for PurpurExtras! Please be as detailed as possible so that we may consider and review the request easier.
      We ask that you search all the issues to avoid a duplicate feature request. If one exists, please reply if you have anything to add.
      Before requesting a new feature, please make sure you are using the latest version and that the feature you are requesting is not already in PurpurExtras.

- type: textarea
  attributes:
    label: The idea/problem for your feature request.
    description: >
      Please give some context for this request. Why do you want it added?
    placeholder: It's hard to ... ; I'm unable to ...
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the solution you'd like.
    description: A clear and concise description of what you want.
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe alternatives you've considered.
    description: |
      List any alternatives you might have tried to get the feature you want.
      Also explain why these are not preferable to the solution you suggest.
  validations:
    required: false

- type: checkboxes
  attributes:
    label: Agreements
    description: Please agree to the following.
    options:
      - label: I have searched for and ensured there isn't already an open issue regarding this.
        required: true
      - label: I have ensured the feature I'm requesting isn't already in the latest supported PurpurExtras version.
        required: true

- type: textarea
  attributes:
    label: Anything Else?
    description: Add any other context or screenshots about the feature request below.
