name: Build
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@master
        name: Setup JDK
        with:
          distribution: 'microsoft'
          java-version: 17
          cache: 'gradle'
      - name: Build with Gradle
        run: gradle shadowJar --no-daemon --stacktrace
      - name: Delete cache on Failure
        if: ${{ failure() }}
        uses: TheRealRyGuy/clear-cache-action@master
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
